name: test coverage

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install
        run: make install
      uses: actions/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE_ID }}
      with:
        coverageCommand: make test-coverage
        coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
        debug: true